Add custom backend metrics propoal link to custom lb policies
grpc/grpc.io pull request #1304
Opened 2024-06-17 16:58 UTC by purnesh42H

2024-06-17 17:02 UTC, arvindbr8 requested changes
LGTM modulo one comment

2024-06-17 17:03 UTC, arvindbr8 commented on content/en/docs/guides/custom-load-balancing.md
> +For more information on this, please see the custom backend metrics [guide][custom backend metrics]
Seems like you beat me to the fixing it. Thanks

2024-06-17 17:03 UTC, purnesh42H commented on content/en/docs/guides/custom-load-balancing.md
> +For more information on this, please see the custom backend metrics [guide][custom backend metrics]
yes, i changed. Copy paste mistake :)

2024-06-17 17:38 UTC, easwars approved these changes

2024-06-24 16:04 UTC, aranjans commented
@purnesh42H can you rebase with main branch?

2024-06-24 16:05 UTC, temawi approved these changes

2024-06-24 16:06 UTC, merged