Add setup instructions for GA and GTM to README
grpc/grpc.io pull request #1332
Opened 2024-07-24 04:40 UTC by Gayathri625

Updated README.md to include setup and verification instructions for Google Analytics and Google Tag Manager.

2024-07-24 18:20 UTC, arjan-bal requested changes
Please also mention building with the PRODUCTION variable so that GA works.

2024-07-24 20:38 UTC, gnossen commented
Seems like https://github.com/grpc/grpc.io/pull/1332#pullrequestreview-2197470755 still needs to be resolved, so holding off on merging for now.

2024-07-25 14:58 UTC, arjan-bal commented
> Please also mention building with the PRODUCTION variable so that GA works.

@Gayathri625  For reference, this seems to be the block that only includes analytics scripts when in production mode: https://github.com/grpc/grpc.io-docsy/blob/ba20af1c9044e3ad8d83ead5153b243c88539038/layouts/partials/head.html#L55-L61

2024-07-26 11:48 UTC, Gayathri625 commented
> I see that we load GTM scripts in non-prod also in #1313. Can you have a similar prod env check for them also? You can do that in a separate PR.

check for production environment: [#1335](https://github.com/grpc/grpc.io/pull/1335)

2024-07-26 12:05 UTC, arjan-bal approved these changes
LGTM!

2024-07-26 12:05 UTC, arjan-bal commented on README.md
> +Build the site by setting Hugo environment to production to make sure GA and GTM work correctly
nit: Can omit "correctly", they will not work at all without it,
>...make sure GA and GTM work.

2024-07-29 16:49 UTC, gnossen approved these changes

2024-07-29 16:49 UTC, merged